export default [
{"id":"1",
  "nameProduct":"Pants Beige Men",
  "Price":"200",
  "Gendre":"Men",
  "typeC":"Pants",
  "Info":{
    "color":"Maron",
    "type":"sport",
    "seller":"23",
    "imgUrl":"https://www.iciw.com/bilder/artiklar/zoom/ICIW-409_1.jpg?m=1568128302"
  }
},
{"id":"2","nameProduct":"Cargo Black Men",
  "Price":"300",
  "Gendre":"Men",
  "typeC":"Pants",
  "Info":{
    "color":"black",
    "type":"Sport",
    "seller":"12",
    "imgUrl":"https://www.iciw.com/bilder/artiklar/ICIW-535.jpg?m=1571233914"
  }
},
{"id":"3","nameProduct":"Mens Casual Pant",
  "Price":"199",
  "Gendre":"Men",
  "typeC":"Pants",
  "Info":{
    "color":"Maron",
    "type":"class",
    "seller":"52",
    "imgUrl":"https://5.imimg.com/data5/TF/IW/MY-17554435/men-casual-pant-500x500.jpg"
  }
},
{"id":"4","nameProduct":"Tassel Oxfords Men Formal",
  "Price":"38",
  "Gendre":"Men",
  "typeC":"Shoes",
  "Info":{
    "color":"Maron",
    "type":"class",
    "seller":"9",
    "imgUrl":"https://ng.jumia.is/unsafe/fit-in/680x680/filters:fill(white)/product/26/346123/5.jpg?3283"
  }
},
{"id":"5","nameProduct":"Oora Grey Running Shoes",
  "Price":"404",
  "Gendre":"Men",
  "typeC":"Shoes",
  "Info":{
    "color":"white",
    "type":"sport",
    "seller":"20",
    "imgUrl":"https://cdn.shopclues.com/images1/thumbnails/104158/320/320/148648730-104158193-1592481791.jpg"
  }
},
{"id":"6","nameProduct":" Casual Shoes Fashion Sports Shoes",
  "Price":"30",
  "Gendre":"Men",
  "typeC":"Shoes",
  "Info":{
    "color":"black",
    "type":"sport",
    "seller":"35",
    "imgUrl":"https://sc01.alicdn.com/kf/HTB1fmXui2BNTKJjy0Fdq6APpVXaO/230827862/HTB1fmXui2BNTKJjy0Fdq6APpVXaO.jpg_.webp"
  }
},
{"id":"7","nameProduct":" Casual Shoes Fashion Sports Shoes",
  "Price":"30",
  "Gendre":"Men",
  "typeC":"Shoes",
  "Info":{
    "color":"black",
    "type":"sport",
    "seller":"35",
    "imgUrl":"https://sc01.alicdn.com/kf/HTB1fmXui2BNTKJjy0Fdq6APpVXaO/230827862/HTB1fmXui2BNTKJjy0Fdq6APpVXaO.jpg_.webp"
  }
},
{"id":"8","nameProduct":" Casual Shoes Fashion Sports Shoes",
  "Price":"30",
  "Gendre":"Men",
  "typeC":"Shoes",
  "Info":{
    "color":"black",
    "type":"sport",
    "seller":"35",
    "imgUrl":"https://sc01.alicdn.com/kf/HTB1fmXui2BNTKJjy0Fdq6APpVXaO/230827862/HTB1fmXui2BNTKJjy0Fdq6APpVXaO.jpg_.webp"
  }
},
{"id":"9","nameProduct":"Pants Beige Men 1",
  "Price":"200",
  "Gendre":"Men",
  "typeC":"Pants",
  "Info":{
    "color":"Maron",
    "type":"sport",
    "seller":"23",
    "imgUrl":"https://www.iciw.com/bilder/artiklar/zoom/ICIW-409_1.jpg?m=1568128302"
  }
},
{"id":"10","nameProduct":"Pants Beige Men 1",
  "Price":"200",
  "Gendre":"Men",
  "typeC":"Pants",
  "Info":{
    "color":"Maron",
    "type":"sport",
    "seller":"23",
    "imgUrl":"https://www.iciw.com/bilder/artiklar/zoom/ICIW-409_1.jpg?m=1568128302"
  }
},
{"id":"11","nameProduct":"Pants Beige Men 1",
  "Price":"200",
  "Gendre":"Men",
  "typeC":"Pants",
  "Info":{
    "color":"Maron",
    "type":"sport",
    "seller":"23",
    "imgUrl":"https://www.iciw.com/bilder/artiklar/zoom/ICIW-409_1.jpg?m=1568128302"
  }
},
{"id":"12","nameProduct":"Cargo Black Men 1",
  "Price":"300",
  "Gendre":"Men",
  "typeC":"Pants",
  "Info":{
    "color":"black",
    "type":"Sport",
    "seller":"12",
    "imgUrl":"https://www.iciw.com/bilder/artiklar/ICIW-535.jpg?m=1571233914"
  }
},
{"id":"13","nameProduct":"Mens Casual Pant 1",
  "Price":"199",
  "Gendre":"Men",
  "typeC":"Pants",
  "Info":{
    "color":"Maron",
    "type":"class",
    "seller":"52",
    "imgUrl":"https://5.imimg.com/data5/TF/IW/MY-17554435/men-casual-pant-500x500.jpg"
  }
},
{"id":"14","nameProduct":"Tassel Oxfords Men Formal 1",
  "Price":"38",
  "Gendre":"Men",
  "typeC":"Shoes",
  "Info":{
    "color":"Maron",
    "type":"class",
    "seller":"9",
    "imgUrl":"https://ng.jumia.is/unsafe/fit-in/680x680/filters:fill(white)/product/26/346123/5.jpg?3283"
  }
},
{"id":"15","nameProduct":"Oora Grey Running Shoes 1",
  "Price":"404",
  "Gendre":"Men",
  "typeC":"Shoes",
  "Info":{
    "color":"white",
    "type":"sport",
    "seller":"20",
    "imgUrl":"https://cdn.shopclues.com/images1/thumbnails/104158/320/320/148648730-104158193-1592481791.jpg"
  }
},
{"id":"16","nameProduct":" Casual Shoes Fashion Sports Shoes 1",
  "Price":"30",
  "Gendre":"Men",
  "typeC":"Shoes",
  "Info":{
    "color":"black",
    "type":"sport",
    "seller":"35",
    "imgUrl":"https://sc01.alicdn.com/kf/HTB1fmXui2BNTKJjy0Fdq6APpVXaO/230827862/HTB1fmXui2BNTKJjy0Fdq6APpVXaO.jpg_.webp"
  }
},
{"id":"17","nameProduct":"Pants Beige Men 2",
  "Price":"200",
  "Gendre":"Men",
  "typeC":"Pants",
  "Info":{
    "color":"Maron",
    "type":"sport",
    "seller":"23",
    "imgUrl":"https://www.iciw.com/bilder/artiklar/zoom/ICIW-409_1.jpg?m=1568128302"
  }
},
{"id":"18","nameProduct":"Cargo Black Men 2",
  "Price":"300",
  "Gendre":"Men",
  "typeC":"Pants",
  "Info":{
    "color":"black",
    "type":"Sport",
    "seller":"12",
    "imgUrl":"https://www.iciw.com/bilder/artiklar/ICIW-535.jpg?m=1571233914"
  }
},
{"id":"19","nameProduct":"Mens Casual Pant 2",
  "Price":"199",
  "Gendre":"Men",
  "typeC":"Pants",
  "Info":{
    "color":"Maron",
    "type":"class",
    "seller":"52",
    "imgUrl":"https://5.imimg.com/data5/TF/IW/MY-17554435/men-casual-pant-500x500.jpg"
  }
},
{"id":"20","nameProduct":"Tassel Oxfords Men Formal 2",
  "Price":"38",
  "Gendre":"Men",
  "typeC":"Shoes",
  "Info":{
    "color":"Maron",
    "type":"class",
    "seller":"9",
    "imgUrl":"https://ng.jumia.is/unsafe/fit-in/680x680/filters:fill(white)/product/26/346123/5.jpg?3283"
  }
},
{"id":"21","nameProduct":"Oora Grey Running Shoes 2",
  "Price":"404",
  "Gendre":"Men",
  "typeC":"Shoes",
  "Info":{
    "color":"white",
    "type":"sport",
    "seller":"20",
    "imgUrl":"https://cdn.shopclues.com/images1/thumbnails/104158/320/320/148648730-104158193-1592481791.jpg"
  }
},
{"id":"22","nameProduct":"Oora Grey Running Shoes 2",
  "Price":"404",
  "Gendre":"Men",
  "typeC":"Shoes",
  "Info":{
    "color":"white",
    "type":"sport",
    "seller":"20",
    "imgUrl":"https://cdn.shopclues.com/images1/thumbnails/104158/320/320/148648730-104158193-1592481791.jpg"
  }
},
{"id":"23","nameProduct":"Oora Grey Running Shoes 2",
  "Price":"404",
  "Gendre":"Men",
  "typeC":"Shoes",
  "Info":{
    "color":"white",
    "type":"sport",
    "seller":"20",
    "imgUrl":"https://cdn.shopclues.com/images1/thumbnails/104158/320/320/148648730-104158193-1592481791.jpg"
  }
},
{"id":"24","nameProduct":" Casual Shoes Fashion Sports Shoes 2",
  "Price":"30",
  "Gendre":"Men",
  "typeC":"Shoes",
  "Info":{
    "color":"black",
    "type":"sport",
    "seller":"35",
    "imgUrl":"https://sc01.alicdn.com/kf/HTB1fmXui2BNTKJjy0Fdq6APpVXaO/230827862/HTB1fmXui2BNTKJjy0Fdq6APpVXaO.jpg_.webp"
  }
}
]
