export default [
{"nameProduct":"Pants Beige Men",
  "Price":"200",
  "Gendre":"Men",
  "typeC":"Pants",
  "Info":{
    "color":"Maron",
    "type":"sport",
    "seller":"23",
    "imgUrl":"https://www.iciw.com/bilder/artiklar/zoom/ICIW-409_1.jpg?m=1568128302"
  }
},
{"nameProduct":"Cargo Black Men",
  "Price":"300",
  "Gendre":"Men",
  "typeC":"Pants",
  "Info":{
    "color":"black",
    "type":"Sport",
    "seller":"12",
    "imgUrl":"https://www.iciw.com/bilder/artiklar/ICIW-535.jpg?m=1571233914"
  }
},
{"nameProduct":"Mens Casual Pant",
  "Price":"199",
  "Gendre":"Men",
  "typeC":"Pants",
  "Info":{
    "color":"Maron",
    "type":"class",
    "seller":"52",
    "imgUrl":"https://5.imimg.com/data5/TF/IW/MY-17554435/men-casual-pant-500x500.jpg"
  }
},
{"nameProduct":"Tassel Oxfords Men Formal",
  "Price":"38",
  "Gendre":"Men",
  "typeC":"Shoes",
  "Info":{
    "color":"Maron",
    "type":"class",
    "seller":"9",
    "imgUrl":"https://ng.jumia.is/unsafe/fit-in/680x680/filters:fill(white)/product/26/346123/5.jpg?3283"
  }
},
{"nameProduct":"Oora Grey Running Shoes",
  "Price":"404",
  "Gendre":"Men",
  "typeC":"Shoes",
  "Info":{
    "color":"white",
    "type":"sport",
    "seller":"20",
    "imgUrl":"https://cdn.shopclues.com/images1/thumbnails/104158/320/320/148648730-104158193-1592481791.jpg"
  }
},
{"nameProduct":" Casual Shoes Fashion Sports Shoes",
  "Price":"30",
  "Gendre":"Men",
  "typeC":"Shoes",
  "Info":{
    "color":"black",
    "type":"sport",
    "seller":"35",
    "imgUrl":"https://sc01.alicdn.com/kf/HTB1fmXui2BNTKJjy0Fdq6APpVXaO/230827862/HTB1fmXui2BNTKJjy0Fdq6APpVXaO.jpg_.webp"
  }
},
{"nameProduct":" Casual Shoes Fashion Sports Shoes",
  "Price":"30",
  "Gendre":"Men",
  "typeC":"Shoes",
  "Info":{
    "color":"black",
    "type":"sport",
    "seller":"35",
    "imgUrl":"https://sc01.alicdn.com/kf/HTB1fmXui2BNTKJjy0Fdq6APpVXaO/230827862/HTB1fmXui2BNTKJjy0Fdq6APpVXaO.jpg_.webp"
  }
},
{"nameProduct":" Casual Shoes Fashion Sports Shoes",
  "Price":"30",
  "Gendre":"Men",
  "typeC":"Shoes",
  "Info":{
    "color":"black",
    "type":"sport",
    "seller":"35",
    "imgUrl":"https://sc01.alicdn.com/kf/HTB1fmXui2BNTKJjy0Fdq6APpVXaO/230827862/HTB1fmXui2BNTKJjy0Fdq6APpVXaO.jpg_.webp"
  }
},
{"nameProduct":"Pants Beige Men 1",
  "Price":"200",
  "Gendre":"Men",
  "typeC":"Pants",
  "Info":{
    "color":"Maron",
    "type":"sport",
    "seller":"23",
    "imgUrl":"https://www.iciw.com/bilder/artiklar/zoom/ICIW-409_1.jpg?m=1568128302"
  }
},
{"nameProduct":"Pants Beige Men 1",
  "Price":"200",
  "Gendre":"Men",
  "typeC":"Pants",
  "Info":{
    "color":"Maron",
    "type":"sport",
    "seller":"23",
    "imgUrl":"https://www.iciw.com/bilder/artiklar/zoom/ICIW-409_1.jpg?m=1568128302"
  }
},
{"nameProduct":"Pants Beige Men 1",
  "Price":"200",
  "Gendre":"Men",
  "typeC":"Pants",
  "Info":{
    "color":"Maron",
    "type":"sport",
    "seller":"23",
    "imgUrl":"https://www.iciw.com/bilder/artiklar/zoom/ICIW-409_1.jpg?m=1568128302"
  }
},
{"nameProduct":"Cargo Black Men 1",
  "Price":"300",
  "Gendre":"Men",
  "typeC":"Pants",
  "Info":{
    "color":"black",
    "type":"Sport",
    "seller":"12",
    "imgUrl":"https://www.iciw.com/bilder/artiklar/ICIW-535.jpg?m=1571233914"
  }
},
{"nameProduct":"Mens Casual Pant 1",
  "Price":"199",
  "Gendre":"Men",
  "typeC":"Pants",
  "Info":{
    "color":"Maron",
    "type":"class",
    "seller":"52",
    "imgUrl":"https://5.imimg.com/data5/TF/IW/MY-17554435/men-casual-pant-500x500.jpg"
  }
},
{"nameProduct":"Tassel Oxfords Men Formal 1",
  "Price":"38",
  "Gendre":"Men",
  "typeC":"Shoes",
  "Info":{
    "color":"Maron",
    "type":"class",
    "seller":"9",
    "imgUrl":"https://ng.jumia.is/unsafe/fit-in/680x680/filters:fill(white)/product/26/346123/5.jpg?3283"
  }
},
{"nameProduct":"Oora Grey Running Shoes 1",
  "Price":"404",
  "Gendre":"Men",
  "typeC":"Shoes",
  "Info":{
    "color":"white",
    "type":"sport",
    "seller":"20",
    "imgUrl":"https://cdn.shopclues.com/images1/thumbnails/104158/320/320/148648730-104158193-1592481791.jpg"
  }
},
{"nameProduct":" Casual Shoes Fashion Sports Shoes 1",
  "Price":"30",
  "Gendre":"Men",
  "typeC":"Shoes",
  "Info":{
    "color":"black",
    "type":"sport",
    "seller":"35",
    "imgUrl":"https://sc01.alicdn.com/kf/HTB1fmXui2BNTKJjy0Fdq6APpVXaO/230827862/HTB1fmXui2BNTKJjy0Fdq6APpVXaO.jpg_.webp"
  }
},
{"nameProduct":"Pants Beige Men 2",
  "Price":"200",
  "Gendre":"Men",
  "typeC":"Pants",
  "Info":{
    "color":"Maron",
    "type":"sport",
    "seller":"23",
    "imgUrl":"https://www.iciw.com/bilder/artiklar/zoom/ICIW-409_1.jpg?m=1568128302"
  }
},
{"nameProduct":"Cargo Black Men 2",
  "Price":"300",
  "Gendre":"Men",
  "typeC":"Pants",
  "Info":{
    "color":"black",
    "type":"Sport",
    "seller":"12",
    "imgUrl":"https://www.iciw.com/bilder/artiklar/ICIW-535.jpg?m=1571233914"
  }
},
{"nameProduct":"Mens Casual Pant 2",
  "Price":"199",
  "Gendre":"Men",
  "typeC":"Pants",
  "Info":{
    "color":"Maron",
    "type":"class",
    "seller":"52",
    "imgUrl":"https://5.imimg.com/data5/TF/IW/MY-17554435/men-casual-pant-500x500.jpg"
  }
},
{"nameProduct":"Tassel Oxfords Men Formal 2",
  "Price":"38",
  "Gendre":"Men",
  "typeC":"Shoes",
  "Info":{
    "color":"Maron",
    "type":"class",
    "seller":"9",
    "imgUrl":"https://ng.jumia.is/unsafe/fit-in/680x680/filters:fill(white)/product/26/346123/5.jpg?3283"
  }
},
{"nameProduct":"Oora Grey Running Shoes 2",
  "Price":"404",
  "Gendre":"Men",
  "typeC":"Shoes",
  "Info":{
    "color":"white",
    "type":"sport",
    "seller":"20",
    "imgUrl":"https://cdn.shopclues.com/images1/thumbnails/104158/320/320/148648730-104158193-1592481791.jpg"
  }
},
{"nameProduct":"Oora Grey Running Shoes 2",
  "Price":"404",
  "Gendre":"Men",
  "typeC":"Shoes",
  "Info":{
    "color":"white",
    "type":"sport",
    "seller":"20",
    "imgUrl":"https://cdn.shopclues.com/images1/thumbnails/104158/320/320/148648730-104158193-1592481791.jpg"
  }
},
{"nameProduct":"Oora Grey Running Shoes 2",
  "Price":"404",
  "Gendre":"Men",
  "typeC":"Shoes",
  "Info":{
    "color":"white",
    "type":"sport",
    "seller":"20",
    "imgUrl":"https://cdn.shopclues.com/images1/thumbnails/104158/320/320/148648730-104158193-1592481791.jpg"
  }
},
{"nameProduct":" Casual Shoes Fashion Sports Shoes 2",
  "Price":"30",
  "Gendre":"Men",
  "typeC":"Shoes",
  "Info":{
    "color":"black",
    "type":"sport",
    "seller":"35",
    "imgUrl":"https://sc01.alicdn.com/kf/HTB1fmXui2BNTKJjy0Fdq6APpVXaO/230827862/HTB1fmXui2BNTKJjy0Fdq6APpVXaO.jpg_.webp"
  }
}
]
